# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail
cache: cocoapods
podfile: Example/Podfile
before_install:
 - brew update
 - rvm install ruby-2.2.5
 - gem install cocoapods
 - gem install xcpretty -N
 - brew install swiftlint || true
 - pod install --project-directory=Example
script:
 - set -o pipefail
 - xcodebuild test -enableCodeCoverage YES -workspace Example/nullfx.crc.xcworkspace -scheme nullfx.crc-Example -sdk iphonesimulator12.0 -destination "platform=iOS Simulator,name=iPhone XS" | xcpretty -c
# - swiftlint
 - pod lib lint
